version: '3.8'
services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -U $POSTGRES_USER --dbname=$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 2
  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
    network_mode: host
    command: sh -c "sleep 5 && npx prisma migrate deploy && npm start"
    env_file:
      - .env
